name: Rust

on:
  push:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Cache deps
      uses: actions/cache@v2
      with:
        path: |
            /usr/local/cargo/registry
            ./target
        key: ${{ runner.os }}-${{ hashFiles('**/Cargo.toml') }}

    - name: Build static
      uses: stevenleadbeater/rust-musl-builder@master
      with:
          args: /bin/bash -c "cargo build --release --target=x86_64-unknown-linux-musl"

    - name: Upload binary
      uses: actions/upload-artifact@v2
      with:
        name: server
        path: target/x86_64-unknown-linux-musl/release/pastebin
