name: Rust

on:
  push:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Cache deps
      uses: actions/cache@v2
      with:
        path: ./cargo-home
        key: v1-cargo
        restore-keys: |
          v1-cargo

    - name: Cache target
      uses: actions/cache@v2
      with:
        path: ./target
        key: v1-target
        restore-keys: |
          v1-target

    - name: Build static
      uses: stevenleadbeater/rust-musl-builder@master
      with:
          args: /bin/bash -c "CARGO_HOME=./cargo-home cargo build --release --target=x86_64-unknown-linux-musl"

    - name: Upload binary
      uses: actions/upload-artifact@v2
      with:
        name: server
        path: target/x86_64-unknown-linux-musl/release/pastebin
